### ISSUE TITLE
What is com.twitter.commons:zookeeper:0.1.1?

### ISSUE THREAD

**Issue by jdanbrown** [boundary/ordasity#8]
I see the jar in boundary's repo [here](http://maven.boundary.com/artifactory/external/com/twitter/common/zookeeper/), but not in twitter's repo [here](http://maven.twttr.com/com/twitter/common/zookeeper/) or [here](http://maven.twttr.com/com/twitter/common/zookeeper/client/), and I see nothing else relevant [on google](https://www.google.com/search?q=com.twitter.commons:zookeeper:0.1.1).

Judging by these two issues on twitter/commons,
- https://github.com/twitter/commons/issues/10
- https://github.com/twitter/commons/pull/11

it sounds like there's a forked boundary repo somewhere that was going to get merged back upstream, but it got stalled. If so, what's the status of that? Is the source available, at least?

I'm interested because I just tripped [a ZooKeeperClient bug that was recently fixed](https://github.com/twitter/commons/commit/49d8f99f554457cedb9002ba79c51ea3d11c4850#diff-33), and I'd like to upgrade to one of the [more recent com.twitter.commons.zookeeper:client versions](http://maven.twttr.com/com/twitter/common/zookeeper/client/), or at least apply the twitter patch to com.twitter.commons:zookeeper:0.1.1 in the meantime.

**Comment by jdanbrown** [comment]
Clarification: I do have the source jar for com.twitter.commons:zookeeper:0.1.1 from [here](http://maven.boundary.com/artifactory/external/com/twitter/common/zookeeper/0.1.1/), but I'm wondering if there's a repo somewhere that I can fork and push the twitter patch to. Alternatively, I might just make an ad-hoc repo from the source jar or something.

**Comment by jdanbrown** [comment]
[Ad-hoc repo](https://github.com/jdanbrown/zookeeper-client-ordasity) created and [patched](https://github.com/jdanbrown/zookeeper-client-ordasity/commit/b6f8ae2b7f0bac05d0e9fbac504f4d1ebc729f50). I'll go with this for now. The questions above still stand.

**Comment by jdanbrown** [comment]
Just diagnosed and fixed [another bug in ZooKeeperClient](https://github.com/jdanbrown/zookeeper-client-ordasity/commit/35ac99fa16005c9646452bc898ebf62b9db87a59) that was causing `onLeave`/`onJoin` races around cluster expiration when using https://github.com/jdanbrown/ordasity/commit/4f8f71bba124381992358c8d4916efc04a47c36f from #15, which exposes the race because it [causes the ZooKeeperClient watchers to be registered in a different order](https://github.com/jdanbrown/ordasity/commit/4f8f71bba124381992358c8d4916efc04a47c36f#L0R182). Turns out [twitter fixed this ZooKeeperClient bug upstream](https://github.com/twitter/commons/blob/8ea556778b879a611a03364d303c6723d254e704/src/java/com/twitter/common/zookeeper/ZooKeeperClient.java#L181) a long time ago.

This is another request to resolve twitter/commons/pull/11 so we can sync up with the latest twitter/commons and avoid some of these issues. ;) What needs to be done—maybe I can help?

**Comment by eric** [comment]
twitter/commons#165 was just merged. Hopefully there will be a release soon that will allow ordasity to be updated to use it.

**Comment by pkwarren** [comment]
Release 0.5.8 of Ordasity is now available. This switches to the upstream Twitter Commons ZK client. There is a small API difference - ZKMapListener is just Listener in the upstream client, so you will need to update your imports accordingly.
